# Generated by Django 6.0.2 on 2026-02-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_area_code', models.CharField(max_length=50, unique=True, verbose_name='厂区编码')),
                ('name', models.CharField(max_length=100, verbose_name='厂区名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '厂区',
                'verbose_name_plural': '厂区管理',
                'db_table': 'factory_area',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_code', models.CharField(max_length=50, unique=True, verbose_name='楼层编码')),
                ('name', models.CharField(max_length=100, verbose_name='楼层名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '楼层',
                'verbose_name_plural': '楼层管理',
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=50, verbose_name='线体编码')),
                ('line_name', models.CharField(max_length=100, verbose_name='线体名称')),
                ('owner_person_id', models.CharField(max_length=50, verbose_name='责任人ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('factory_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_area.factoryarea', verbose_name='所属厂区')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory_area.floor', verbose_name='所在楼层')),
            ],
            options={
                'verbose_name': '线体',
                'verbose_name_plural': '线体管理',
                'db_table': 'line',
                'unique_together': {('factory_area', 'line_code')},
            },
        ),
    ]
