# Generated by Django 6.0.2 on 2026-02-10 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('calibration_sop', '校验SOP'), ('calibration_tool_list', '校验器具/工具清单'), ('manual', '说明书'), ('quote', '报价单'), ('certificate', '证书'), ('other', '其他')], max_length=30, unique=True, verbose_name='附件类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '附件类别',
                'verbose_name_plural': '附件类别管理',
                'db_table': 'attachment_type',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type_id', models.CharField(max_length=50, unique=True, verbose_name='类型ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('device_category', models.CharField(choices=[('self_made', '自制设备'), ('purchased', '采购设备'), ('calibration_tool', '校验器具')], max_length=20, verbose_name='设备类别')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌/厂商')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('calibration_method', models.CharField(choices=[('internal', '内部校准'), ('external', '外部送检'), ('hybrid', '内外结合'), ('none', '无需校准')], default='none', max_length=20, verbose_name='送校方式')),
                ('maintenance_required', models.BooleanField(default=True, verbose_name='需要保养')),
                ('calibration_required', models.BooleanField(default=False, verbose_name='需要校正')),
                ('maintenance_interval_days', models.IntegerField(default=180, verbose_name='保养周期(天)')),
                ('calibration_interval_days', models.IntegerField(default=365, verbose_name='校正周期(天)')),
                ('maintenance_duration_min', models.IntegerField(default=60, verbose_name='保养预计工时(分钟)')),
                ('calibration_duration_min', models.IntegerField(default=120, verbose_name='校正预计工时(分钟)')),
                ('estimated_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估单价')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('cost_source', models.CharField(blank=True, max_length=100, verbose_name='成本来源')),
                ('cost_updated_at', models.DateField(blank=True, null=True, verbose_name='成本更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型管理',
                'db_table': 'equipment_type',
                'ordering': ['equipment_type_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeAttachmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('attachment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory_area.attachmenttype', verbose_name='附件类别')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_requirements', to='factory_area.equipmenttype', verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备类型附件要求',
                'verbose_name_plural': '设备类型附件要求',
                'db_table': 'equipment_type_attachment_requirement',
                'unique_together': {('equipment_type', 'attachment_type')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeToolRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField(default=1, verbose_name='需要数量')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_requirements', to='factory_area.equipmenttype', verbose_name='设备类型')),
                ('required_tool_type', models.ForeignKey(limit_choices_to={'device_category': 'calibration_tool'}, on_delete=django.db.models.deletion.CASCADE, related_name='required_by_equipment_types', to='factory_area.equipmenttype', verbose_name='所需校验器具类型')),
            ],
            options={
                'verbose_name': '设备类型工具要求',
                'verbose_name_plural': '设备类型工具要求',
                'db_table': 'equipment_type_tool_requirement',
                'unique_together': {('equipment_type', 'required_tool_type')},
            },
        ),
    ]
