# Generated by Django 6.0.2 on 2026-02-10 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_area', '0002_attachmenttype_equipmenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False, verbose_name='设备ID')),
                ('ppid', models.CharField(help_text='每台设备的唯一标识，必填', max_length=100, unique=True, verbose_name='PPID')),
                ('asset_tag', models.CharField(blank=True, help_text='若有固定资产编号则填写', max_length=100, null=True, verbose_name='固定资产编号')),
                ('device_code', models.CharField(blank=True, help_text='现场编号/铭牌编号/内部编号', max_length=100, verbose_name='设备编码')),
                ('device_name', models.CharField(blank=True, help_text='如不填写，将自动生成：类型名称+PPID', max_length=200, verbose_name='设备名称')),
                ('department_name', models.CharField(blank=True, max_length=100, verbose_name='归属部门/团队')),
                ('keeper', models.CharField(blank=True, help_text='保管人/责任人ID', max_length=100, verbose_name='保管责任人')),
                ('rfid_tag', models.CharField(blank=True, help_text='有值则必须唯一', max_length=100, null=True, unique=True, verbose_name='RFID标签')),
                ('inventory_external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='盘点系统ID')),
                ('rfid_enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='RFID纳入时间')),
                ('operational_state', models.CharField(choices=[('IN_USE', '使用中'), ('SPARE', '备品/备用'), ('IDLE', '闲置可用'), ('WAITING_FOR_REPAIR', '待维修'), ('IN_MAINTENANCE', '维修/保养/校正中'), ('QUARANTINED', '隔离/冻结'), ('PENDING_DISPOSAL', '待报废/待处置'), ('OUT_OF_SERVICE', '已报废/不可用')], default='IDLE', max_length=20, verbose_name='运行状态')),
                ('location_type', models.CharField(choices=[('LINE', '线体'), ('WAREHOUSE', '仓库'), ('LAB', '实验室'), ('OTHER', '其他')], default='OTHER', max_length=20, verbose_name='位置类型')),
                ('location_text', models.CharField(blank=True, help_text='非线体位置，如仓库/维修间/库位', max_length=200, verbose_name='位置描述')),
                ('area', models.CharField(blank=True, help_text='线上设备：例CC10、CC11等；非线上设备：例仓库、维修间等', max_length=100, verbose_name='区域/工位')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_type', models.ForeignKey(help_text='必须选择一个设备类型', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='factory_area.equipmenttype', verbose_name='设备类型')),
                ('line', models.ForeignKey(blank=True, help_text="当位置类型为'线体'时填写", null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory_area.line', verbose_name='所在线体')),
            ],
            options={
                'verbose_name': '设备实例',
                'verbose_name_plural': '设备实例管理',
                'db_table': 'device',
                'ordering': ['-created_at'],
            },
        ),
    ]
