# Generated by Django 6.0.2 on 2026-02-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_area', '0003_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['line_name'], 'verbose_name': '线体', 'verbose_name_plural': '线体管理'},
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='线体名称'),
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_code',
        ),
    ]
