# Generated by Django 6.0.2 on 2026-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_area', '0004_alter_line_options_alter_line_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='device_category',
            field=models.CharField(choices=[('self_made', '自制设备'), ('purchased', '客供设备'), ('calibration_tool', '市购设备')], max_length=20, verbose_name='设备类别'),
        ),
    ]
