# Generated by Django 6.0.2 on 2026-03-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory_area', '0005_alter_equipmenttype_device_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMaintenanceProfile',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='maintenance_profile', serialize=False, to='factory_area.device', verbose_name='设备实例')),
                ('enable_maintenance', models.BooleanField(default=True, verbose_name='是否纳入维保体系')),
                ('use_type_defaults', models.BooleanField(default=True, verbose_name='使用类型默认值')),
                ('maintenance_required', models.BooleanField(default=True, verbose_name='是否需要保养（覆盖）')),
                ('calibration_required', models.BooleanField(default=False, verbose_name='是否需要校正（覆盖）')),
                ('maintenance_interval_days', models.IntegerField(default=180, verbose_name='保养周期(天,覆盖)')),
                ('calibration_interval_days', models.IntegerField(default=365, verbose_name='校正周期(天,覆盖)')),
                ('maintenance_duration_min', models.IntegerField(default=60, verbose_name='保养预计工时(分钟,覆盖)')),
                ('calibration_duration_min', models.IntegerField(default=120, verbose_name='校正预计工时(分钟,覆盖)')),
                ('effective_from', models.DateTimeField(auto_now_add=True, verbose_name='规则生效时间')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, verbose_name='更新人')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
            ],
            options={
                'verbose_name': '设备纳管配置',
                'verbose_name_plural': '设备纳管配置管理',
                'db_table': 'device_maintenance_profile',
            },
        ),
    ]
